package com.example.directory_l5;

public class Array {

    // МАССИВ ДЛЯ ЛЕГКОГО УРОВНЯ (ПЕРВАЯ ПОЛОВИНА ТАНКИ АРМИИ СОЮЗНИКОВ, ВТОРАЯ ПОЛОВИНА НЕМЕЦКИЕ ТАНКИ).
    final int[] img = {
            R.drawable.us1,
            R.drawable.us2,
            R.drawable.us3,
            R.drawable.us4,
            R.drawable.us5,
            R.drawable.us6,
            R.drawable.us7,
            R.drawable.us8,
            R.drawable.us9,
            R.drawable.us10,
            R.drawable.us11,
            R.drawable.us12,
            R.drawable.us13,
            R.drawable.us14,
            R.drawable.us15,
            R.drawable.us16,
            R.drawable.us17,
            R.drawable.us18,
            R.drawable.us19,
            R.drawable.us20,
            R.drawable.us21,
            R.drawable.us22,
            R.drawable.us23,
            R.drawable.us24,
            R.drawable.us25,
            R.drawable.us26,
            R.drawable.us27,
            R.drawable.us28,
            R.drawable.us29,
            R.drawable.us30,
            R.drawable.us31,
            R.drawable.us32,
            R.drawable.us33,
            R.drawable.us34,
            R.drawable.us35,
            R.drawable.us36,
            R.drawable.us37,
            R.drawable.us38,
            R.drawable.us39,
            R.drawable.us40,
            R.drawable.us41,
            R.drawable.us42,
            R.drawable.us43,
            R.drawable.us44,
            R.drawable.us45,
            R.drawable.us46,
            R.drawable.us47,
            R.drawable.us48,
            R.drawable.us49,
            R.drawable.us50,
            R.drawable.us51,
            R.drawable.us52,
            R.drawable.us53,
            R.drawable.us54,
            R.drawable.us55,
            R.drawable.us56,
            R.drawable.us57,
            R.drawable.us58,
            R.drawable.us59,
            R.drawable.us60,
            R.drawable.b_13_5,
            R.drawable.b_221_1,
            R.drawable.b_221_3,
            R.drawable.b_221_4,
            R.drawable.b_222_1,
            R.drawable.b_251_3,
            R.drawable.b_254_3,
            R.drawable.s_brumb_2,
            R.drawable.b_p42_3,
            R.drawable.s_brumb_2,
            R.drawable.s_brumb_4,
            R.drawable.s_grill_1,
            R.drawable.s_grill_5,
            R.drawable.s_jgdpan_1,
            R.drawable.s_jgdpan_3,
            R.drawable.s_jgdpan_4,
            R.drawable.s_jgdttig_3,
            R.drawable.s_mar2_1,
            R.drawable.s_mar2_5,
            R.drawable.s_mar3_3,
            R.drawable.s_nash_1,
            R.drawable.s_pzjg1_2,
            R.drawable.s_pzjg1_3,
            R.drawable.s_pzjg1_4,
            R.drawable.s_stpz_4,
            R.drawable.s_stug3_1,
            R.drawable.s_stug3_3,
            R.drawable.s_stug3_4,
            R.drawable.s_stug4_1,
            R.drawable.s_stug42_1,
            R.drawable.s_sturem_1,
            R.drawable.s_sturem_2,
            R.drawable.s_sturem_3,
            R.drawable.s_sturtig_1,
            R.drawable.s_sturtig_2,
            R.drawable.s_sturtig_4,
            R.drawable.s_sturtig_5,
            R.drawable.s_wesp_1,
            R.drawable.s_wesp_3,
            R.drawable.t_maus_1,
            R.drawable.t_maus_5,
            R.drawable.t_nbfz_5,
            R.drawable.t_pz1_1,
            R.drawable.t_pz1_4,
            R.drawable.t_pz2_1,
            R.drawable.t_pz2_2,
            R.drawable.t_pz2_4,
            R.drawable.t_pz2_5,
            R.drawable.t_pz2l_4,
            R.drawable.t_pz3_4,
            R.drawable.t_pz4_4,
            R.drawable.t_pz4_5,
            R.drawable.t_pz5_1,
            R.drawable.t_pz5_2,
            R.drawable.t_pz5_5,
            R.drawable.t_pz6_1,
            R.drawable.t_pz6_2,
            R.drawable.t_pz6_4,
            R.drawable.t_pz6_5,
            R.drawable.t_pz62_3,

    };
    //________________________________________________________________________________________________________________________________


    //Аррай вопросов пока оставить
    public String mQuestions[] = {
            "1/10",
            "2/10",
            "3/10",
            "4/10",
            "5/10",
            "6/10",
            "7/10",
            "8/10",
            "9/10",
            "10/10",

    };



    // Массив танков для тяжелого и среднего теста (ТОЛЬКО НЕМЕЦКИЕ!!!!!!)
    public int imageTanksHard[] = {
            R.drawable.t_pz1_1, R.drawable.t_pz2_1, R.drawable.t_pz2l_1,R.drawable.t_nbfz_1,R.drawable.t_pz35_1,R.drawable.t_pz38_1,
            R.drawable.t_pz3_1,R.drawable.t_pz4_1,R.drawable.t_pz5_1,R.drawable.t_pz6_1,R.drawable.t_pz62_1,R.drawable.t_maus_1,
            R.drawable.s_bis_1,R.drawable.s_pzjg1_1,R.drawable.s_hez_1,R.drawable.s_stpz_1,R.drawable.s_grill_1,R.drawable.s_mar2_1,
            R.drawable.s_mar3_1,R.drawable.s_wesp_1,R.drawable.s_stug3_1,R.drawable.s_stug4_1,R.drawable.s_stug42_1,R.drawable.s_brumb_1,R.drawable.s_nash_1,R.drawable.s_humm_1,
            R.drawable.s_jgpz4_1,R.drawable.s_dickm_1,R.drawable.s_jgdpan_1,R.drawable.s_sturem_1,R.drawable.s_ferd_1,R.drawable.s_sturtig_1,R.drawable.s_jgdttig_1,R.drawable.s_karl_1,
            R.drawable.b_13_1, R.drawable.b_adgz_1, R.drawable.b_221_1,R.drawable.b_222_1,R.drawable.b_231_1,R.drawable.b_panar_1,
            R.drawable.b_234_1,R.drawable.b_247_1,R.drawable.b_250_1,R.drawable.b_251_1,R.drawable.b_254_1,R.drawable.b_p42_1,
            R.drawable.t_pz1_2, R.drawable.t_pz2_2, R.drawable.t_pz2l_2,R.drawable.t_nbfz_2,R.drawable.t_pz35_2,R.drawable.t_pz38_2,
            R.drawable.t_pz3_2,R.drawable.t_pz4_2,R.drawable.t_pz5_2,R.drawable.t_pz6_2,R.drawable.t_pz62_2,R.drawable.t_maus_2,
            R.drawable.s_bis_2,R.drawable.s_pzjg1_2,R.drawable.s_hez_2,R.drawable.s_stpz_2,R.drawable.s_grill_2,R.drawable.s_mar2_2,
            R.drawable.s_mar3_2,R.drawable.s_wesp_2,R.drawable.s_stug3_2,R.drawable.s_stug4_2,R.drawable.s_stug42_2,R.drawable.s_brumb_2,R.drawable.s_nash_2,R.drawable.s_humm_2,
            R.drawable.s_jgpz4_2,R.drawable.s_dickm_2,R.drawable.s_jgdpan_2,R.drawable.s_sturem_2,R.drawable.s_ferd_2,R.drawable.s_sturtig_2,R.drawable.s_jgdttig_2,R.drawable.s_karl_2,
            R.drawable.b_13_2, R.drawable.b_adgz_2, R.drawable.b_221_2,R.drawable.b_222_2,R.drawable.b_231_1,R.drawable.b_panar_2,
            R.drawable.b_234_2,R.drawable.b_247_2,R.drawable.b_250_2,R.drawable.b_251_2,R.drawable.b_254_2,R.drawable.b_p42_2,
            R.drawable.t_pz1_3, R.drawable.t_pz2_3, R.drawable.t_pz2l_3,R.drawable.t_nbfz_3,R.drawable.t_pz35_3,R.drawable.t_pz38_3,
            R.drawable.t_pz3_3,R.drawable.t_pz4_3,R.drawable.t_pz5_3,R.drawable.t_pz6_3,R.drawable.t_pz62_3,R.drawable.t_maus_3,
            R.drawable.s_bis_3,R.drawable.s_pzjg1_3,R.drawable.s_hez_3,R.drawable.s_stpz_3,R.drawable.s_grill_3,R.drawable.s_mar2_3,
            R.drawable.s_mar3_3,R.drawable.s_wesp_3,R.drawable.s_stug3_3,R.drawable.s_stug4_3,R.drawable.s_stug42_3,R.drawable.s_brumb_3,R.drawable.s_nash_3,R.drawable.s_humm_3,
            R.drawable.s_jgpz4_3,R.drawable.s_dickm_3,R.drawable.s_jgdpan_3,R.drawable.s_sturem_3,R.drawable.s_ferd_3,R.drawable.s_sturtig_3,R.drawable.s_jgdttig_3,R.drawable.s_karl_3,
            R.drawable.b_13_3, R.drawable.b_adgz_3, R.drawable.b_221_3,R.drawable.b_222_3,R.drawable.b_231_1,R.drawable.b_panar_3,
            R.drawable.b_234_3,R.drawable.b_247_3,R.drawable.b_250_3,R.drawable.b_251_3,R.drawable.b_254_3,R.drawable.b_p42_3,
            R.drawable.t_pz1_4, R.drawable.t_pz2_4, R.drawable.t_pz2l_4,R.drawable.t_nbfz_4,R.drawable.t_pz35_4,R.drawable.t_pz38_4,
            R.drawable.t_pz3_4,R.drawable.t_pz4_4,R.drawable.t_pz5_4,R.drawable.t_pz6_4,R.drawable.t_pz62_4,R.drawable.t_maus_4,
            R.drawable.s_bis_4,R.drawable.s_pzjg1_4,R.drawable.s_hez_4,R.drawable.s_stpz_4,R.drawable.s_grill_4,R.drawable.s_mar2_4,
            R.drawable.s_mar3_4,R.drawable.s_wesp_4,R.drawable.s_stug3_4,R.drawable.s_stug4_4,R.drawable.s_stug42_4,R.drawable.s_brumb_4,R.drawable.s_nash_4,R.drawable.s_humm_4,
            R.drawable.s_jgpz4_4,R.drawable.s_dickm_4,R.drawable.s_jgdpan_4,R.drawable.s_sturem_4,R.drawable.s_ferd_4,R.drawable.s_sturtig_4,R.drawable.s_jgdttig_4,R.drawable.s_karl_4,
            R.drawable.b_13_4, R.drawable.b_adgz_4, R.drawable.b_221_4,R.drawable.b_222_4,R.drawable.b_231_1,R.drawable.b_panar_4,
            R.drawable.b_234_4,R.drawable.b_247_4,R.drawable.b_250_4,R.drawable.b_251_4,R.drawable.b_254_4,R.drawable.b_p42_4,
            R.drawable.t_pz1_5, R.drawable.t_pz2_5, R.drawable.t_pz2l_5,R.drawable.t_nbfz_5,R.drawable.t_pz35_5,R.drawable.t_pz38_5,
            R.drawable.t_pz3_5,R.drawable.t_pz4_5,R.drawable.t_pz5_5,R.drawable.t_pz6_5,R.drawable.t_pz62_5,R.drawable.t_maus_5,
            R.drawable.s_bis_5,R.drawable.s_pzjg1_5,R.drawable.s_hez_5,R.drawable.s_stpz_5,R.drawable.s_grill_5,R.drawable.s_mar2_5,
            R.drawable.s_mar3_5,R.drawable.s_wesp_5,R.drawable.s_stug3_5,R.drawable.s_stug4_5,R.drawable.s_stug42_5,R.drawable.s_brumb_5,R.drawable.s_nash_5,R.drawable.s_humm_5,
            R.drawable.s_jgpz4_5,R.drawable.s_dickm_5,R.drawable.s_jgdpan_5,R.drawable.s_sturem_5,R.drawable.s_ferd_5,R.drawable.s_sturtig_5,R.drawable.s_jgdttig_5,R.drawable.s_karl_5,
            R.drawable.b_13_5, R.drawable.b_adgz_5, R.drawable.b_221_5,R.drawable.b_222_5,R.drawable.b_231_1,R.drawable.b_panar_5,
            R.drawable.b_234_5,R.drawable.b_247_5,R.drawable.b_250_5,R.drawable.b_251_5,R.drawable.b_254_5,R.drawable.b_p42_5,
    };



    // Массив варианты ответов для тяжелого теста
    public String mChoise[][] = {
            {"PzKpfw VI Ausf. B «Tiger II»", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.I", "Sd.Kfz.234"},
            {"Pz.Kpfw. II", "Sd.Kfz.222", "PzKpfw V «Panther»", "StuG IV (Sturmgeschütz IV)"},
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", "Pz.Kpfw.I", "Sd.Kfz.247"},
            {"Hetzer (Jagdpanzer 38)", "ADGZ", "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            {"15 cm Panzerwerfer 42 auf Sf", "Sd.Kfz.222", "Pz.Spah.204(f)", "PzKpfw.35(t) (LT vz.35)"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "Sd.Kfz.231 (6-Rad)", "«Ягдтигр» (нем. Jagdtiger)", "SdKfz 251"},
            {"Sd.Kfz.234", "Pz.Kpfw.III", "Pz.Kpfw. II", "JagdPz IV"},
            {"Sturmpanzer I Bison", "PzKpfw.35(t) (LT vz.35)", "PzKpfw IV ", "Sd.Kfz.13"},
            {"JagdPz IV", "PzKpfw IV ", "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw.38(t) (LT vz.38)", "StuG IV (Sturmgeschütz IV)", "Sd.Kfz.247"},
            {"Wespe ", "PzKpfw VI Ausf. B «Tiger II»", "Pz.Kpfw.I", "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)", "Dicker Max ", "PzKpfw VI «Tiger»"},
            {"Marder II ", "Sturmpanzer I Bison", "Pz.Kpfw. II", "PzKpfw V «Panther»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "Marder III ", "Panzerjäger I ", "SdKfz 250"},
            {"Sd.Kfz.231 (6-Rad)", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw. II «Luchs»", "Hetzer (Jagdpanzer 38)"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", "Marder III ", "Sturmpanzer IV"},
            {"Sd.Kfz.247", "Grille", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw.I"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw. II", "Marder II ", "Wespe "},
            {"Grille", "Wespe ", "Hetzer (Jagdpanzer 38)", "Marder III "},
            {"Wespe ", "JagdPz IV", "Marder II ", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.247", "Sturmgeschütz III (StuG III)", "PzKpfw V «Panther»", "ADGZ"},
            {"Pz.Kpfw. II", "SdKfz 250", "StuG IV (Sturmgeschütz IV)", "Hetzer (Jagdpanzer 38)"},
            {"Dicker Max ", "Pzkpfw.VIII «Maus»", "Pz.Kpfw.38(t) (LT vz.38)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sturmpanzer IV", "Pz.Kpfw.I","Sturmpanzer I Bison", "Sturmpanzer II "},
            {"StuH 42 (10,5 cm Sturmhaubitze 42)", "Nashorn ", "«Фердинанд» (нем. Ferdinand)", "ADGZ"},
            {"«Ягдпантера» (нем. Jagdpanther)", "Nashorn ", "Hummel", "PzKpfw V «Panther»"},
            {"Sd.Kfz.247", "Pz.Kpfw. II «Luchs»", "PzKpfw VI Ausf. B «Tiger II»", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV", "Самоходная мортира«Карл»", "Hummel"},
            {"Sd.Kfz.247", "«Ягдпантера» (нем. Jagdpanther)", "PzKpfw VI «Tiger»", "SdKfz 250"},
            {"Pz.Spah.204(f)", "Panzerkampfwagen Neubaufahrzeug", "Sturer Emil (нем. Sturer Emil)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II «Luchs»", "Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw IV ", "«Фердинанд» (нем. Ferdinand)", "Hummel"},
            {"Marder III ", "«Ягдтигр» (нем. Jagdtiger)", "JagdPz IV", "«Ягдпантера» (нем. Jagdpanther)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw.35(t) (LT vz.35)", "Самоходная мортира«Карл»", "«Ягдтигр» (нем. Jagdtiger)"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", "JagdPz IV", "Pz.Kpfw. II"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "ADGZ", "StuH 42 (10,5 cm Sturmhaubitze 42)", "JagdPz IV"},
            {"PzKpfw.35(t) (LT vz.35)", "Hetzer (Jagdpanzer 38)", "Sd.Kfz.221", "Grille"},
            {"SdKfz 250", "Hetzer (Jagdpanzer 38)", "PzKpfw VI «Tiger»", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)", "StuH 42 (10,5 cm Sturmhaubitze 42)", "Pz.Kpfw.III"},
            {"Pz.Kpfw.I", "Sd.Kfz.13","Pz.Spah.204(f)", "«Фердинанд» (нем. Ferdinand)"},
            {"Sd.Kfz.234", "Grille", "Sd.Kfz.221", "Pz.Kpfw. II"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II", "Sd.Kfz.247", "«Штурмтигр» (нем. Sturmtiger)"},
            {"SdKfz 250", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.III", "Hetzer (Jagdpanzer 38)"},
            {"PzKpfw VI «Tiger»", "StuH 42 (10,5 cm Sturmhaubitze 42)", "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254", "Marder II ", "Pzkpfw.VIII «Maus»"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III", "Sd.Kfz.13", "PzKpfw VI Ausf. B «Tiger II»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.I", "Sd.Kfz.234"},
            {"Pz.Kpfw. II", "Sd.Kfz.222", "PzKpfw V «Panther»", "StuG IV (Sturmgeschütz IV)"},
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", "Pz.Kpfw.I", "Sd.Kfz.247"},
            {"Hetzer (Jagdpanzer 38)", "ADGZ", "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            {"15 cm Panzerwerfer 42 auf Sf", "Sd.Kfz.222", "Pz.Spah.204(f)", "PzKpfw.35(t) (LT vz.35)"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "Sd.Kfz.231 (6-Rad)", "«Ягдтигр» (нем. Jagdtiger)", "SdKfz 251"},
            {"Sd.Kfz.234", "Pz.Kpfw.III", "Pz.Kpfw. II", "JagdPz IV"},
            {"Sturmpanzer I Bison", "PzKpfw.35(t) (LT vz.35)", "PzKpfw IV ", "Sd.Kfz.13"},
            {"JagdPz IV", "PzKpfw IV ", "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw.38(t) (LT vz.38)", "StuG IV (Sturmgeschütz IV)", "Sd.Kfz.247"},
            {"Wespe ", "PzKpfw VI Ausf. B «Tiger II»", "Pz.Kpfw.I", "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)", "Dicker Max ", "PzKpfw VI «Tiger»"},
            {"Marder II ", "Sturmpanzer I Bison", "Pz.Kpfw. II", "PzKpfw V «Panther»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "Marder III ", "Panzerjäger I ", "SdKfz 250"},
            {"Sd.Kfz.231 (6-Rad)", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw. II «Luchs»", "Hetzer (Jagdpanzer 38)"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", "Marder III ", "Sturmpanzer IV"},
            {"Sd.Kfz.247", "Grille", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw.I"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw. II", "Marder II ", "Wespe "},
            {"Grille", "Wespe ", "Hetzer (Jagdpanzer 38)", "Marder III "},
            {"Wespe ", "JagdPz IV", "Marder II ", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.247", "Sturmgeschütz III (StuG III)", "PzKpfw V «Panther»", "ADGZ"},
            {"Pz.Kpfw. II", "SdKfz 250", "StuG IV (Sturmgeschütz IV)", "Hetzer (Jagdpanzer 38)"},
            {"Dicker Max ", "Pzkpfw.VIII «Maus»", "Pz.Kpfw.38(t) (LT vz.38)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sturmpanzer IV", "Pz.Kpfw.I","Sturmpanzer I Bison", "Sturmpanzer II "},
            {"StuH 42 (10,5 cm Sturmhaubitze 42)", "Nashorn ", "«Фердинанд» (нем. Ferdinand)", "ADGZ"},
            {"«Ягдпантера» (нем. Jagdpanther)", "Nashorn ", "Hummel", "PzKpfw V «Panther»"},
            {"Sd.Kfz.247", "Pz.Kpfw. II «Luchs»", "PzKpfw VI Ausf. B «Tiger II»", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV", "Самоходная мортира«Карл»", "Hummel"},
            {"Sd.Kfz.247", "«Ягдпантера» (нем. Jagdpanther)", "PzKpfw VI «Tiger»", "SdKfz 250"},
            {"Pz.Spah.204(f)", "Panzerkampfwagen Neubaufahrzeug", "Sturer Emil (нем. Sturer Emil)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II «Luchs»", "Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw IV ", "«Фердинанд» (нем. Ferdinand)", "Hummel"},
            {"Marder III ", "«Ягдтигр» (нем. Jagdtiger)", "JagdPz IV", "«Ягдпантера» (нем. Jagdpanther)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw.35(t) (LT vz.35)", "Самоходная мортира«Карл»", "«Ягдтигр» (нем. Jagdtiger)"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", "JagdPz IV", "Pz.Kpfw. II"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "ADGZ", "StuH 42 (10,5 cm Sturmhaubitze 42)", "JagdPz IV"},
            {"PzKpfw.35(t) (LT vz.35)", "Hetzer (Jagdpanzer 38)", "Sd.Kfz.221", "Grille"},
            {"SdKfz 250", "Hetzer (Jagdpanzer 38)", "PzKpfw VI «Tiger»", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)", "StuH 42 (10,5 cm Sturmhaubitze 42)", "Pz.Kpfw.III"},
            {"Pz.Kpfw.I", "Sd.Kfz.13","Pz.Spah.204(f)", "«Фердинанд» (нем. Ferdinand)"},
            {"Sd.Kfz.234", "Grille", "Sd.Kfz.221", "Pz.Kpfw. II"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II", "Sd.Kfz.247", "«Штурмтигр» (нем. Sturmtiger)"},
            {"SdKfz 250", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.III", "Hetzer (Jagdpanzer 38)"},
            {"PzKpfw VI «Tiger»", "StuH 42 (10,5 cm Sturmhaubitze 42)", "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254", "Marder II ", "Pzkpfw.VIII «Maus»"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III", "Sd.Kfz.13", "PzKpfw VI Ausf. B «Tiger II»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.I", "Sd.Kfz.234"},
            {"Pz.Kpfw. II", "Sd.Kfz.222", "PzKpfw V «Panther»", "StuG IV (Sturmgeschütz IV)"},
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", "Pz.Kpfw.I", "Sd.Kfz.247"},
            {"Hetzer (Jagdpanzer 38)", "ADGZ", "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            {"15 cm Panzerwerfer 42 auf Sf", "Sd.Kfz.222", "Pz.Spah.204(f)", "PzKpfw.35(t) (LT vz.35)"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "Sd.Kfz.231 (6-Rad)", "«Ягдтигр» (нем. Jagdtiger)", "SdKfz 251"},
            {"Sd.Kfz.234", "Pz.Kpfw.III", "Pz.Kpfw. II", "JagdPz IV"},
            {"Sturmpanzer I Bison", "PzKpfw.35(t) (LT vz.35)", "PzKpfw IV ", "Sd.Kfz.13"},
            {"JagdPz IV", "PzKpfw IV ", "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw.38(t) (LT vz.38)", "StuG IV (Sturmgeschütz IV)", "Sd.Kfz.247"},
            {"Wespe ", "PzKpfw VI Ausf. B «Tiger II»", "Pz.Kpfw.I", "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)", "Dicker Max ", "PzKpfw VI «Tiger»"},
            {"Marder II ", "Sturmpanzer I Bison", "Pz.Kpfw. II", "PzKpfw V «Panther»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "Marder III ", "Panzerjäger I ", "SdKfz 250"},
            {"Sd.Kfz.231 (6-Rad)", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw. II «Luchs»", "Hetzer (Jagdpanzer 38)"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", "Marder III ", "Sturmpanzer IV"},
            {"Sd.Kfz.247", "Grille", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw.I"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw. II", "Marder II ", "Wespe "},
            {"Grille", "Wespe ", "Hetzer (Jagdpanzer 38)", "Marder III "},
            {"Wespe ", "JagdPz IV", "Marder II ", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.247", "Sturmgeschütz III (StuG III)", "PzKpfw V «Panther»", "ADGZ"},
            {"Pz.Kpfw. II", "SdKfz 250", "StuG IV (Sturmgeschütz IV)", "Hetzer (Jagdpanzer 38)"},
            {"Dicker Max ", "Pzkpfw.VIII «Maus»", "Pz.Kpfw.38(t) (LT vz.38)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sturmpanzer IV", "Pz.Kpfw.I","Sturmpanzer I Bison", "Sturmpanzer II "},
            {"StuH 42 (10,5 cm Sturmhaubitze 42)", "Nashorn ", "«Фердинанд» (нем. Ferdinand)", "ADGZ"},
            {"«Ягдпантера» (нем. Jagdpanther)", "Nashorn ", "Hummel", "PzKpfw V «Panther»"},
            {"Sd.Kfz.247", "Pz.Kpfw. II «Luchs»", "PzKpfw VI Ausf. B «Tiger II»", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV", "Самоходная мортира«Карл»", "Hummel"},
            {"Sd.Kfz.247", "«Ягдпантера» (нем. Jagdpanther)", "PzKpfw VI «Tiger»", "SdKfz 250"},
            {"Pz.Spah.204(f)", "Panzerkampfwagen Neubaufahrzeug", "Sturer Emil (нем. Sturer Emil)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II «Luchs»", "Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw IV ", "«Фердинанд» (нем. Ferdinand)", "Hummel"},
            {"Marder III ", "«Ягдтигр» (нем. Jagdtiger)", "JagdPz IV", "«Ягдпантера» (нем. Jagdpanther)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw.35(t) (LT vz.35)", "Самоходная мортира«Карл»", "«Ягдтигр» (нем. Jagdtiger)"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", "JagdPz IV", "Pz.Kpfw. II"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "ADGZ", "StuH 42 (10,5 cm Sturmhaubitze 42)", "JagdPz IV"},
            {"PzKpfw.35(t) (LT vz.35)", "Hetzer (Jagdpanzer 38)", "Sd.Kfz.221", "Grille"},
            {"SdKfz 250", "Hetzer (Jagdpanzer 38)", "PzKpfw VI «Tiger»", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)", "StuH 42 (10,5 cm Sturmhaubitze 42)", "Pz.Kpfw.III"},
            {"Pz.Kpfw.I", "Sd.Kfz.13","Pz.Spah.204(f)", "«Фердинанд» (нем. Ferdinand)"},
            {"Sd.Kfz.234", "Grille", "Sd.Kfz.221", "Pz.Kpfw. II"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II", "Sd.Kfz.247", "«Штурмтигр» (нем. Sturmtiger)"},
            {"SdKfz 250", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.III", "Hetzer (Jagdpanzer 38)"},
            {"PzKpfw VI «Tiger»", "StuH 42 (10,5 cm Sturmhaubitze 42)", "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254", "Marder II ", "Pzkpfw.VIII «Maus»"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III", "Sd.Kfz.13", "PzKpfw VI Ausf. B «Tiger II»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.I", "Sd.Kfz.234"},
            {"Pz.Kpfw. II", "Sd.Kfz.222", "PzKpfw V «Panther»", "StuG IV (Sturmgeschütz IV)"},
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", "Pz.Kpfw.I", "Sd.Kfz.247"},
            {"Hetzer (Jagdpanzer 38)", "ADGZ", "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            {"15 cm Panzerwerfer 42 auf Sf", "Sd.Kfz.222", "Pz.Spah.204(f)", "PzKpfw.35(t) (LT vz.35)"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "Sd.Kfz.231 (6-Rad)", "«Ягдтигр» (нем. Jagdtiger)", "SdKfz 251"},
            {"Sd.Kfz.234", "Pz.Kpfw.III", "Pz.Kpfw. II", "JagdPz IV"},
            {"Sturmpanzer I Bison", "PzKpfw.35(t) (LT vz.35)", "PzKpfw IV ", "Sd.Kfz.13"},
            {"JagdPz IV", "PzKpfw IV ", "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw.38(t) (LT vz.38)", "StuG IV (Sturmgeschütz IV)", "Sd.Kfz.247"},
            {"Wespe ", "PzKpfw VI Ausf. B «Tiger II»", "Pz.Kpfw.I", "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)", "Dicker Max ", "PzKpfw VI «Tiger»"},
            {"Marder II ", "Sturmpanzer I Bison", "Pz.Kpfw. II", "PzKpfw V «Panther»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "Marder III ", "Panzerjäger I ", "SdKfz 250"},
            {"Sd.Kfz.231 (6-Rad)", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw. II «Luchs»", "Hetzer (Jagdpanzer 38)"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", "Marder III ", "Sturmpanzer IV"},
            {"Sd.Kfz.247", "Grille", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw.I"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw. II", "Marder II ", "Wespe "},
            {"Grille", "Wespe ", "Hetzer (Jagdpanzer 38)", "Marder III "},
            {"Wespe ", "JagdPz IV", "Marder II ", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.247", "Sturmgeschütz III (StuG III)", "PzKpfw V «Panther»", "ADGZ"},
            {"Pz.Kpfw. II", "SdKfz 250", "StuG IV (Sturmgeschütz IV)", "Hetzer (Jagdpanzer 38)"},
            {"Dicker Max ", "Pzkpfw.VIII «Maus»", "Pz.Kpfw.38(t) (LT vz.38)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sturmpanzer IV", "Pz.Kpfw.I","Sturmpanzer I Bison", "Sturmpanzer II "},
            {"StuH 42 (10,5 cm Sturmhaubitze 42)", "Nashorn ", "«Фердинанд» (нем. Ferdinand)", "ADGZ"},
            {"«Ягдпантера» (нем. Jagdpanther)", "Nashorn ", "Hummel", "PzKpfw V «Panther»"},
            {"Sd.Kfz.247", "Pz.Kpfw. II «Luchs»", "PzKpfw VI Ausf. B «Tiger II»", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV", "Самоходная мортира«Карл»", "Hummel"},
            {"Sd.Kfz.247", "«Ягдпантера» (нем. Jagdpanther)", "PzKpfw VI «Tiger»", "SdKfz 250"},
            {"Pz.Spah.204(f)", "Panzerkampfwagen Neubaufahrzeug", "Sturer Emil (нем. Sturer Emil)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II «Luchs»", "Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw IV ", "«Фердинанд» (нем. Ferdinand)", "Hummel"},
            {"Marder III ", "«Ягдтигр» (нем. Jagdtiger)", "JagdPz IV", "«Ягдпантера» (нем. Jagdpanther)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw.35(t) (LT vz.35)", "Самоходная мортира«Карл»", "«Ягдтигр» (нем. Jagdtiger)"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", "JagdPz IV", "Pz.Kpfw. II"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "ADGZ", "StuH 42 (10,5 cm Sturmhaubitze 42)", "JagdPz IV"},
            {"PzKpfw.35(t) (LT vz.35)", "Hetzer (Jagdpanzer 38)", "Sd.Kfz.221", "Grille"},
            {"SdKfz 250", "Hetzer (Jagdpanzer 38)", "PzKpfw VI «Tiger»", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)", "StuH 42 (10,5 cm Sturmhaubitze 42)", "Pz.Kpfw.III"},
            {"Pz.Kpfw.I", "Sd.Kfz.13","Pz.Spah.204(f)", "«Фердинанд» (нем. Ferdinand)"},
            {"Sd.Kfz.234", "Grille", "Sd.Kfz.221", "Pz.Kpfw. II"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II", "Sd.Kfz.247", "«Штурмтигр» (нем. Sturmtiger)"},
            {"SdKfz 250", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.III", "Hetzer (Jagdpanzer 38)"},
            {"PzKpfw VI «Tiger»", "StuH 42 (10,5 cm Sturmhaubitze 42)", "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254", "Marder II ", "Pzkpfw.VIII «Maus»"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III", "Sd.Kfz.13", "PzKpfw VI Ausf. B «Tiger II»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.I", "Sd.Kfz.234"},
            {"Pz.Kpfw. II", "Sd.Kfz.222", "PzKpfw V «Panther»", "StuG IV (Sturmgeschütz IV)"},
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", "Pz.Kpfw.I", "Sd.Kfz.247"},
            {"Hetzer (Jagdpanzer 38)", "ADGZ", "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            {"15 cm Panzerwerfer 42 auf Sf", "Sd.Kfz.222", "Pz.Spah.204(f)", "PzKpfw.35(t) (LT vz.35)"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "Sd.Kfz.231 (6-Rad)", "«Ягдтигр» (нем. Jagdtiger)", "SdKfz 251"},
            {"Sd.Kfz.234", "Pz.Kpfw.III", "Pz.Kpfw. II", "JagdPz IV"},
            {"Sturmpanzer I Bison", "PzKpfw.35(t) (LT vz.35)", "PzKpfw IV ", "Sd.Kfz.13"},
            {"JagdPz IV", "PzKpfw IV ", "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw.38(t) (LT vz.38)", "StuG IV (Sturmgeschütz IV)", "Sd.Kfz.247"},
            {"Wespe ", "PzKpfw VI Ausf. B «Tiger II»", "Pz.Kpfw.I", "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)", "Dicker Max ", "PzKpfw VI «Tiger»"},
            {"Marder II ", "Sturmpanzer I Bison", "Pz.Kpfw. II", "PzKpfw V «Panther»"},
            {"PzKpfw VI Ausf. B «Tiger II»", "Marder III ", "Panzerjäger I ", "SdKfz 250"},
            {"Sd.Kfz.231 (6-Rad)", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw. II «Luchs»", "Hetzer (Jagdpanzer 38)"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", "Marder III ", "Sturmpanzer IV"},
            {"Sd.Kfz.247", "Grille", "«Ягдпантера» (нем. Jagdpanther)", "Pz.Kpfw.I"},
            {"PzKpfw VI «Tiger»", "Pz.Kpfw. II", "Marder II ", "Wespe "},
            {"Grille", "Wespe ", "Hetzer (Jagdpanzer 38)", "Marder III "},
            {"Wespe ", "JagdPz IV", "Marder II ", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.247", "Sturmgeschütz III (StuG III)", "PzKpfw V «Panther»", "ADGZ"},
            {"Pz.Kpfw. II", "SdKfz 250", "StuG IV (Sturmgeschütz IV)", "Hetzer (Jagdpanzer 38)"},
            {"Dicker Max ", "Pzkpfw.VIII «Maus»", "Pz.Kpfw.38(t) (LT vz.38)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sturmpanzer IV", "Pz.Kpfw.I","Sturmpanzer I Bison", "Sturmpanzer II "},
            {"StuH 42 (10,5 cm Sturmhaubitze 42)", "Nashorn ", "«Фердинанд» (нем. Ferdinand)", "ADGZ"},
            {"«Ягдпантера» (нем. Jagdpanther)", "Nashorn ", "Hummel", "PzKpfw V «Panther»"},
            {"Sd.Kfz.247", "Pz.Kpfw. II «Luchs»", "PzKpfw VI Ausf. B «Tiger II»", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV", "Самоходная мортира«Карл»", "Hummel"},
            {"Sd.Kfz.247", "«Ягдпантера» (нем. Jagdpanther)", "PzKpfw VI «Tiger»", "SdKfz 250"},
            {"Pz.Spah.204(f)", "Panzerkampfwagen Neubaufahrzeug", "Sturer Emil (нем. Sturer Emil)", "StuH 42 (10,5 cm Sturmhaubitze 42)"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II «Luchs»", "Pzkpfw.VIII «Maus»", "«Фердинанд» (нем. Ferdinand)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw IV ", "«Фердинанд» (нем. Ferdinand)", "Hummel"},
            {"Marder III ", "«Ягдтигр» (нем. Jagdtiger)", "JagdPz IV", "«Ягдпантера» (нем. Jagdpanther)"},
            {"«Штурмтигр» (нем. Sturmtiger)", "PzKpfw.35(t) (LT vz.35)", "Самоходная мортира«Карл»", "«Ягдтигр» (нем. Jagdtiger)"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", "JagdPz IV", "Pz.Kpfw. II"},
            {"Pz.Kpfw.38(t) (LT vz.38)", "ADGZ", "StuH 42 (10,5 cm Sturmhaubitze 42)", "JagdPz IV"},
            {"PzKpfw.35(t) (LT vz.35)", "Hetzer (Jagdpanzer 38)", "Sd.Kfz.221", "Grille"},
            {"SdKfz 250", "Hetzer (Jagdpanzer 38)", "PzKpfw VI «Tiger»", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)", "StuH 42 (10,5 cm Sturmhaubitze 42)", "Pz.Kpfw.III"},
            {"Pz.Kpfw.I", "Sd.Kfz.13","Pz.Spah.204(f)", "«Фердинанд» (нем. Ferdinand)"},
            {"Sd.Kfz.234", "Grille", "Sd.Kfz.221", "Pz.Kpfw. II"},
            {"Sd.Kfz.231 (6-Rad)", "Pz.Kpfw. II", "Sd.Kfz.247", "«Штурмтигр» (нем. Sturmtiger)"},
            {"SdKfz 250", "PzKpfw.35(t) (LT vz.35)", "Pz.Kpfw.III", "Hetzer (Jagdpanzer 38)"},
            {"PzKpfw VI «Tiger»", "StuH 42 (10,5 cm Sturmhaubitze 42)", "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254", "Marder II ", "Pzkpfw.VIII «Maus»"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III", "Sd.Kfz.13", "PzKpfw VI Ausf. B «Tiger II»"},




    };


    //МАСИВ ПРАВИЛЬНЫХ ОТВЕТОВ для тяжелого
    public String[] mCorrectAnswer = {"Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t) (LT vz.35)","Pz.Kpfw.38(t) (LT vz.38)","Pz.Kpfw.III","PzKpfw IV ",
            "PzKpfw V «Panther»","PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer (Jagdpanzer 38)","Sturmpanzer II ","Grille",
            "Marder II ","Marder III ","Wespe ","Sturmgeschütz III (StuG III)","StuG IV (Sturmgeschütz IV)","StuH 42 (10,5 cm Sturmhaubitze 42)","Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV",
            "Dicker Max ","«Ягдпантера» (нем. Jagdpanther)","Sturer Emil (нем. Sturer Emil)","«Фердинанд» (нем. Ferdinand)","«Штурмтигр» (нем. Sturmtiger)","«Ягдтигр» (нем. Jagdtiger)","Самоходная мортира«Карл»",
            "Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf",
            "Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t) (LT vz.35)","Pz.Kpfw.38(t) (LT vz.38)","Pz.Kpfw.III","PzKpfw IV ","PzKpfw V «Panther»",
            "PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer (Jagdpanzer 38)","Sturmpanzer II ","Grille","Marder II "
            ,"Marder III ","Wespe ","Sturmgeschütz III (StuG III)","StuG IV (Sturmgeschütz IV)","StuH 42 (10,5 cm Sturmhaubitze 42)","Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV",
            "Dicker Max ","«Ягдпантера» (нем. Jagdpanther)","Sturer Emil (нем. Sturer Emil)","«Фердинанд» (нем. Ferdinand)","«Штурмтигр» (нем. Sturmtiger)","«Ягдтигр» (нем. Jagdtiger)","Самоходная мортира«Карл»",
            "Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf","Pz.Kpfw.I","Pz.Kpfw. II",
            "Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t) (LT vz.35)","Pz.Kpfw.38(t) (LT vz.38)","Pz.Kpfw.III","PzKpfw IV ","PzKpfw V «Panther»","PzKpfw VI «Tiger»",
            "PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer (Jagdpanzer 38)","Sturmpanzer II ","Grille","Marder II ",
            "Marder III ","Wespe ","Sturmgeschütz III (StuG III)","StuG IV (Sturmgeschütz IV)","StuH 42 (10,5 cm Sturmhaubitze 42)","Sturmpanzer IV","Nashorn ","Hummel",
            "JagdPz IV","Dicker Max ","«Ягдпантера» (нем. Jagdpanther)","Sturer Emil (нем. Sturer Emil)","«Фердинанд» (нем. Ferdinand)","«Штурмтигр» (нем. Sturmtiger)","«Ягдтигр» (нем. Jagdtiger)",
            "Самоходная мортира«Карл»","Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254",
            "15 cm Panzerwerfer 42 auf Sf","Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t) (LT vz.35)","Pz.Kpfw.38(t) (LT vz.38)","Pz.Kpfw.III",
            "PzKpfw IV ","PzKpfw V «Panther»","PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer (Jagdpanzer 38)",
            "Sturmpanzer II ","Grille","Marder II ","Marder III ","Wespe ","Sturmgeschütz III (StuG III)","StuG IV (Sturmgeschütz IV)","StuH 42 (10,5 cm Sturmhaubitze 42)",
            "Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV","Dicker Max ","«Ягдпантера» (нем. Jagdpanther)","Sturer Emil (нем. Sturer Emil)","«Фердинанд» (нем. Ferdinand)",
            "«Штурмтигр» (нем. Sturmtiger)","«Ягдтигр» (нем. Jagdtiger)","Самоходная мортира«Карл»","Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234"
            ,"Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf","Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t) (LT vz.35)",
            "Pz.Kpfw.38(t) (LT vz.38)","Pz.Kpfw.III","PzKpfw IV ","PzKpfw V «Panther»","PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ",
            "Hetzer (Jagdpanzer 38)","Sturmpanzer II ","Grille","Marder II ","Marder III ","Wespe ","Sturmgeschütz III (StuG III)","StuG IV (Sturmgeschütz IV)",
            "StuH 42 (10,5 cm Sturmhaubitze 42)","Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV","Dicker Max ","«Ягдпантера» (нем. Jagdpanther)","Sturer Emil (нем. Sturer Emil)",
            "«Фердинанд» (нем. Ferdinand)","«Штурмтигр» (нем. Sturmtiger)","«Ягдтигр» (нем. Jagdtiger)","Самоходная мортира«Карл»","Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)",
            "Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf",
    };


    // ПРИСВАИВАЕМ ИНТ КАРТИНКАМ
    public int mImageQuestion (int a) {
        int imageTank = imageTanksHard[a];
        return imageTank;
    }

    public String getQuestion (int a) {
        String question = mQuestions[a];
        return question;
    }


    //ПРИСВАИВАЕМ ЧЕТЫРЕМ ВАРИАНТАМ ОТВЕТОВ ИНТ
    public String getChoise1 (int a) {
        String choise = mChoise [a][0];
        return choise;
    }

    public String getChoise2 (int a) {
        String choise = mChoise [a][1];
        return choise;
    }

    public String getChoise3 (int a) {
        String choise = mChoise [a][2];
        return choise;
    }

    public String getChoise4 (int a) {
        String choise = mChoise [a][3];
        return choise;
    }

    // ПРИСВАИВАЕМ ИНТ ОТВЕТАМ
    public String getCorrectAnswer (int a){
        String answer = mCorrectAnswer[a];
        return answer;
    }

    //______________________________________________________________________________________________________________







    // Массив варианты ответов для среднего теста
    public String mChoiseMedium[][] = {
            { "PzKpfw.35(t)", "Pz.Kpfw.I", },
            {"Pz.Kpfw. II", "Sd.Kfz.222", },
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", },
            { "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            { "Pz.Spah.204(f)", "PzKpfw.35(t)"},
            {"PzKpfw.38(t)", "Sd.Kfz.231 (6-Rad)", },
            {"Sd.Kfz.234", "Pz.Kpfw.III", },
            { "PzKpfw IV ", "Sd.Kfz.13"},
            { "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»",  "StuG IV", },
            { "PzKpfw VI Ausf. B «Tiger II»",  "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»",  "Dicker Max ", },
            {"Marder II ", "Sturmpanzer I Bison", },
            { "Panzerjäger I ", "SdKfz 250"},
            {"Pz.Kpfw. II «Luchs»", "Hetzer"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", },
            {"Sd.Kfz.247", "Grille", },
            { "Marder II ", "Wespe "},
            { "Hetzer", "Marder III "},
            {"Wespe ", "JagdPz IV", },
            {"Sd.Kfz.247", "StuG III", },
            { "StuG IV", "Hetzer"},
            {"Dicker Max ", "StuH 42"},
            {"Sturmpanzer IV", "Sturmpanzer I Bison",},
            { "Nashorn ", "Ferdinand", },
            { "Nashorn ", "Hummel" },
            {"Sd.Kfz.247", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV",},
            {"Sd.Kfz.247", "Jagdpanther"},
            { "Sturer Emil", "StuH 42"},
            {"Sd.Kfz.231 (6-Rad)", "Ferdinand"},
            {"Sturmtiger",  "Ferdinand"},
            {"Jagdtiger",  "Jagdpanther"},
            {"Sturmtiger",  "Самоходная мортира«Карл»"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", },
            {"PzKpfw.38(t)", "ADGZ", },
            {"Hetzer", "Sd.Kfz.221"},
            {"Hetzer", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)"},
            {"Pz.Kpfw.I", "Pz.Spah.204(f)"},
            {"Sd.Kfz.234", "Grille"},
            {"Sd.Kfz.231 (6-Rad)", "Sd.Kfz.247"},
            {"SdKfz 250", "PzKpfw.35(t)"},
            { "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III"},
            { "PzKpfw.35(t)", "Pz.Kpfw.I", },
            {"Pz.Kpfw. II", "Sd.Kfz.222", },
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", },
            { "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            { "Pz.Spah.204(f)", "PzKpfw.35(t)"},
            {"PzKpfw.38(t)", "Sd.Kfz.231 (6-Rad)", },
            {"Sd.Kfz.234", "Pz.Kpfw.III", },
            { "PzKpfw IV ", "Sd.Kfz.13"},
            { "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»",  "StuG IV", },
            { "PzKpfw VI Ausf. B «Tiger II»",  "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»",  "Dicker Max ", },
            {"Marder II ", "Sturmpanzer I Bison", },
            { "Panzerjäger I ", "SdKfz 250"},
            {"Pz.Kpfw. II «Luchs»", "Hetzer"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", },
            {"Sd.Kfz.247", "Grille", },
            { "Marder II ", "Wespe "},
            { "Hetzer", "Marder III "},
            {"Wespe ", "JagdPz IV", },
            {"Sd.Kfz.247", "StuG III", },
            { "StuG IV", "Hetzer"},
            {"Dicker Max ", "StuH 42"},
            {"Sturmpanzer IV", "Sturmpanzer I Bison",},
            { "Nashorn ", "Ferdinand", },
            { "Nashorn ", "Hummel" },
            {"Sd.Kfz.247", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV",},
            {"Sd.Kfz.247", "Jagdpanther"},
            { "Sturer Emil", "StuH 42"},
            {"Sd.Kfz.231 (6-Rad)", "Ferdinand"},
            {"Sturmtiger",  "Ferdinand"},
            {"Jagdtiger",  "Jagdpanther"},
            {"Sturmtiger",  "Самоходная мортира«Карл»"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", },
            {"PzKpfw.38(t)", "ADGZ", },
            {"Hetzer", "Sd.Kfz.221"},
            {"Hetzer", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)"},
            {"Pz.Kpfw.I", "Pz.Spah.204(f)"},
            {"Sd.Kfz.234", "Grille"},
            {"Sd.Kfz.231 (6-Rad)", "Sd.Kfz.247"},
            {"SdKfz 250", "PzKpfw.35(t)"},
            { "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III"},
            { "PzKpfw.35(t)", "Pz.Kpfw.I", },
            {"Pz.Kpfw. II", "Sd.Kfz.222", },
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", },
            { "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            { "Pz.Spah.204(f)", "PzKpfw.35(t)"},
            {"PzKpfw.38(t)", "Sd.Kfz.231 (6-Rad)", },
            {"Sd.Kfz.234", "Pz.Kpfw.III", },
            { "PzKpfw IV ", "Sd.Kfz.13"},
            { "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»",  "StuG IV", },
            { "PzKpfw VI Ausf. B «Tiger II»",  "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»",  "Dicker Max ", },
            {"Marder II ", "Sturmpanzer I Bison", },
            { "Panzerjäger I ", "SdKfz 250"},
            {"Pz.Kpfw. II «Luchs»", "Hetzer"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", },
            {"Sd.Kfz.247", "Grille", },
            { "Marder II ", "Wespe "},
            { "Hetzer", "Marder III "},
            {"Wespe ", "JagdPz IV", },
            {"Sd.Kfz.247", "StuG III", },
            { "StuG IV", "Hetzer"},
            {"Dicker Max ", "StuH 42"},
            {"Sturmpanzer IV", "Sturmpanzer I Bison",},
            { "Nashorn ", "Ferdinand", },
            { "Nashorn ", "Hummel" },
            {"Sd.Kfz.247", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV",},
            {"Sd.Kfz.247", "Jagdpanther"},
            { "Sturer Emil", "StuH 42"},
            {"Sd.Kfz.231 (6-Rad)", "Ferdinand"},
            {"Sturmtiger",  "Ferdinand"},
            {"Jagdtiger",  "Jagdpanther"},
            {"Sturmtiger",  "Самоходная мортира«Карл»"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", },
            {"PzKpfw.38(t)", "ADGZ", },
            {"Hetzer", "Sd.Kfz.221"},
            {"Hetzer", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)"},
            {"Pz.Kpfw.I", "Pz.Spah.204(f)"},
            {"Sd.Kfz.234", "Grille"},
            {"Sd.Kfz.231 (6-Rad)", "Sd.Kfz.247"},
            {"SdKfz 250", "PzKpfw.35(t)"},
            { "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III"},
            { "PzKpfw.35(t)", "Pz.Kpfw.I", },
            {"Pz.Kpfw. II", "Sd.Kfz.222", },
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", },
            { "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            { "Pz.Spah.204(f)", "PzKpfw.35(t)"},
            {"PzKpfw.38(t)", "Sd.Kfz.231 (6-Rad)", },
            {"Sd.Kfz.234", "Pz.Kpfw.III", },
            { "PzKpfw IV ", "Sd.Kfz.13"},
            { "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»",  "StuG IV", },
            { "PzKpfw VI Ausf. B «Tiger II»",  "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»",  "Dicker Max ", },
            {"Marder II ", "Sturmpanzer I Bison", },
            { "Panzerjäger I ", "SdKfz 250"},
            {"Pz.Kpfw. II «Luchs»", "Hetzer"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", },
            {"Sd.Kfz.247", "Grille", },
            { "Marder II ", "Wespe "},
            { "Hetzer", "Marder III "},
            {"Wespe ", "JagdPz IV", },
            {"Sd.Kfz.247", "StuG III", },
            { "StuG IV", "Hetzer"},
            {"Dicker Max ", "StuH 42"},
            {"Sturmpanzer IV", "Sturmpanzer I Bison",},
            { "Nashorn ", "Ferdinand", },
            { "Nashorn ", "Hummel" },
            {"Sd.Kfz.247", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV",},
            {"Sd.Kfz.247", "Jagdpanther"},
            { "Sturer Emil", "StuH 42"},
            {"Sd.Kfz.231 (6-Rad)", "Ferdinand"},
            {"Sturmtiger",  "Ferdinand"},
            {"Jagdtiger",  "Jagdpanther"},
            {"Sturmtiger",  "Самоходная мортира«Карл»"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", },
            {"PzKpfw.38(t)", "ADGZ", },
            {"Hetzer", "Sd.Kfz.221"},
            {"Hetzer", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)"},
            {"Pz.Kpfw.I", "Pz.Spah.204(f)"},
            {"Sd.Kfz.234", "Grille"},
            {"Sd.Kfz.231 (6-Rad)", "Sd.Kfz.247"},
            {"SdKfz 250", "PzKpfw.35(t)"},
            { "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III"},
            { "PzKpfw.35(t)", "Pz.Kpfw.I", },
            {"Pz.Kpfw. II", "Sd.Kfz.222", },
            {"Sturmpanzer I Bison", "Pz.Kpfw. II «Luchs»", },
            { "Panzerkampfwagen Neubaufahrzeug", "Nashorn "},
            { "Pz.Spah.204(f)", "PzKpfw.35(t)"},
            {"PzKpfw.38(t)", "Sd.Kfz.231 (6-Rad)", },
            {"Sd.Kfz.234", "Pz.Kpfw.III", },
            { "PzKpfw IV ", "Sd.Kfz.13"},
            { "PzKpfw VI «Tiger»", "PzKpfw V «Panther»"},
            {"PzKpfw VI «Tiger»",  "StuG IV", },
            { "PzKpfw VI Ausf. B «Tiger II»",  "Pzkpfw.VIII «Maus»"},
            {"Pzkpfw.VIII «Maus»",  "Dicker Max ", },
            {"Marder II ", "Sturmpanzer I Bison", },
            { "Panzerjäger I ", "SdKfz 250"},
            {"Pz.Kpfw. II «Luchs»", "Hetzer"},
            {"Sturmpanzer II ", "Panzerkampfwagen Neubaufahrzeug", },
            {"Sd.Kfz.247", "Grille", },
            { "Marder II ", "Wespe "},
            { "Hetzer", "Marder III "},
            {"Wespe ", "JagdPz IV", },
            {"Sd.Kfz.247", "StuG III", },
            { "StuG IV", "Hetzer"},
            {"Dicker Max ", "StuH 42"},
            {"Sturmpanzer IV", "Sturmpanzer I Bison",},
            { "Nashorn ", "Ferdinand", },
            { "Nashorn ", "Hummel" },
            {"Sd.Kfz.247", "JagdPz IV"},
            {"Dicker Max ", "JagdPz IV",},
            {"Sd.Kfz.247", "Jagdpanther"},
            { "Sturer Emil", "StuH 42"},
            {"Sd.Kfz.231 (6-Rad)", "Ferdinand"},
            {"Sturmtiger",  "Ferdinand"},
            {"Jagdtiger",  "Jagdpanther"},
            {"Sturmtiger",  "Самоходная мортира«Карл»"},
            {"Sd.Kfz.13", "Pz.Kpfw.III", },
            {"PzKpfw.38(t)", "ADGZ", },
            {"Hetzer", "Sd.Kfz.221"},
            {"Hetzer", "Sd.Kfz.222"},
            {"Marder II ", "Sd.Kfz.231 (6-Rad)"},
            {"Pz.Kpfw.I", "Pz.Spah.204(f)"},
            {"Sd.Kfz.234", "Grille"},
            {"Sd.Kfz.231 (6-Rad)", "Sd.Kfz.247"},
            {"SdKfz 250", "PzKpfw.35(t)"},
            { "SdKfz 251", "Dicker Max "},
            {"Panzerkampfwagen Neubaufahrzeug", "Sd.Kfz 254"},
            {"15 cm Panzerwerfer 42 auf Sf", "Pz.Kpfw.III"},
    };

    // ответы к среднему тесту
    public String mCorrectAnswerMedium[] = {"Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t)","PzKpfw.38(t)","Pz.Kpfw.III","PzKpfw IV ",
            "PzKpfw V «Panther»","PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer","Sturmpanzer II ","Grille",
            "Marder II ","Marder III ","Wespe ","StuG III","StuG IV","StuH 42","Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV",
            "Dicker Max ","Jagdpanther","Sturer Emil","Ferdinand","Sturmtiger","Jagdtiger","Самоходная мортира«Карл»",
            "Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf",
            "Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t)","PzKpfw.38(t)","Pz.Kpfw.III","PzKpfw IV ","PzKpfw V «Panther»",
            "PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer","Sturmpanzer II ","Grille","Marder II "
            ,"Marder III ","Wespe ","StuG III","StuG IV","StuH 42","Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV",
            "Dicker Max ","Jagdpanther","Sturer Emil","Ferdinand","Sturmtiger","Jagdtiger","Самоходная мортира«Карл»",
            "Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf","Pz.Kpfw.I","Pz.Kpfw. II",
            "Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t)","PzKpfw.38(t)","Pz.Kpfw.III","PzKpfw IV ","PzKpfw V «Panther»","PzKpfw VI «Tiger»",
            "PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer","Sturmpanzer II ","Grille","Marder II ",
            "Marder III ","Wespe ","StuG III","StuG IV","StuH 42","Sturmpanzer IV","Nashorn ","Hummel",
            "JagdPz IV","Dicker Max ","Jagdpanther","Sturer Emil","Ferdinand","Sturmtiger","Jagdtiger",
            "Самоходная мортира«Карл»","Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254",
            "15 cm Panzerwerfer 42 auf Sf","Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t)","PzKpfw.38(t)","Pz.Kpfw.III",
            "PzKpfw IV ","PzKpfw V «Panther»","PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ","Hetzer",
            "Sturmpanzer II ","Grille","Marder II ","Marder III ","Wespe ","StuG III","StuG IV","StuH 42",
            "Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV","Dicker Max ","Jagdpanther","Sturer Emil","Ferdinand",
            "Sturmtiger","Jagdtiger","Самоходная мортира«Карл»","Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)","Pz.Spah.204(f)","Sd.Kfz.234"
            ,"Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf","Pz.Kpfw.I","Pz.Kpfw. II","Pz.Kpfw. II «Luchs»","Panzerkampfwagen Neubaufahrzeug","PzKpfw.35(t)",
            "PzKpfw.38(t)","Pz.Kpfw.III","PzKpfw IV ","PzKpfw V «Panther»","PzKpfw VI «Tiger»","PzKpfw VI Ausf. B «Tiger II»","Pzkpfw.VIII «Maus»","Sturmpanzer I Bison","Panzerjäger I ",
            "Hetzer","Sturmpanzer II ","Grille","Marder II ","Marder III ","Wespe ","StuG III","StuG IV",
            "StuH 42","Sturmpanzer IV","Nashorn ","Hummel","JagdPz IV","Dicker Max ","Jagdpanther","Sturer Emil",
            "Ferdinand","Sturmtiger","Jagdtiger","Самоходная мортира«Карл»","Sd.Kfz.13","ADGZ","Sd.Kfz.221","Sd.Kfz.222","Sd.Kfz.231 (6-Rad)",
            "Pz.Spah.204(f)","Sd.Kfz.234","Sd.Kfz.247","SdKfz 250","SdKfz 251","Sd.Kfz 254","15 cm Panzerwerfer 42 auf Sf",
    };

    // ПРИСВАИВАЕМ ИНТ ОТВЕТАМ
    public String getCorrectAnswerMedium (int a){
        String answer = mCorrectAnswerMedium[a];
        return answer;
    }

    //ПРИСВАИВАЕМ двум ВАРИАНТАМ ОТВЕТОВ ИНТ
    public String getChoise1med (int a) {
        String choise = mChoiseMedium [a][0];
        return choise;
    }

    public String getChoise2med (int a) {
        String choise = mChoiseMedium [a][1];
        return choise;
    }

    // ПРИСВАИВАЕМ ИНТ КАРТИНКАМ
    public int mImageQuestionMed (int a) {
        int imageTank = imageTanksHard[a];
        return imageTank;
    }







}